#!/usr/bin/env ruby

require "time"

data = STDIN.read

if ARGV[0] == 'reverse'

  puts data
    .gsub(/%% Date:.*/   , '%% $Date$')
    .gsub(/%% Version:.*/   , '%% $Version$')
    .gsub(/%% Version:.*/   , '%% $Version$')
    .gsub(/\\ProvidesClass{rgg}.*/ , "\\ProvidesClass{rgg}[$ProvidesClassDate$]")

else

  last_date = `git log --pretty=format:"%ai" -1`
  version   = `git describe --tags`
  providesclassdate = Time.parse(last_date).strftime("%Y/%m/%d")

  puts data
    .gsub('$Date$'   , 'Date:    ' + last_date.to_s.chomp)
    .gsub('$Version$', 'Version: ' + version.to_s.chomp)
    .gsub('\ProvidesClass{rgg}[$ProvidesClassDate$]' , "\\ProvidesClass{rgg}[#{providesclassdate}]")

end
