#!/bin/bash

tmpfile=$(mktemp)
./expand_date reverse < rgg.cls | ./expand_date > $tmpfile && cat $tmpfile > rgg.cls

cecho 210 updating $(cecho 2 "\$Version\$"), $(cecho 3 \$Date\$) and $(cecho 4 \$ProvideClassDate\$) in rgg.cls
echo

cecho 2 "From log:     $(git log -1 --pretty=format:"%ai")"
cecho 2 "From rgg.cls: $(grep -w Date rgg.cls |sed 's/%%.Date:\s*//')"

cecho 3 "From log:     $(git describe --tag)"
cecho 3 "From rgg.cls: $(grep -w Version rgg.cls |sed 's/%%.Version:\s*//')"

cecho 4 "From log:     $(git log -1 --pretty=format:"%ai")"
cecho 4 "From rgg.cls: $(grep  ProvidesClass rgg.cls|sed 's/.*\[\(.*\)\]/\1/')"
